Controllers/HowToController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace DYV.Controllers
{
    public class HowToController : Controller
    {
        // GET: /<controller>/
        public IActionResult Manage()
        {
            return View();
        }

        public IActionResult Search()
        {
            return View();
        }

        public IActionResult DayLists()
        {
            return View();
        }
    }
}

Controllers/LegalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace DYV.Controllers
{
    public class LegalController : Controller
    {
        public IActionResult Terms()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Views/Shared/NotFound.cshtml
<h1>404</h1>

Views/Shared/_FooterPartial.cshtml
<footer>
    <div class="row">
        <div class="three columns">
            <h5>Contact Us</h5>
            <address>
                DirectYourVet Ltd. <br />
                2 Kings Road <br />
                Whitley Bay <br />
                Tyne and Wear<br />
                NE26 3BD<br />
            </address>
            <a href="tel:01912801396"><i class="fa fa-phone"></i>0191 2801396</a>
        </div>
        <div class="three columns">
            <h5>Our Philosophy</h5>
            @Html.ActionLink("Technology", "Technology", "Home") <br />
            @Html.ActionLink("Security", "Security", "Home") <br />
            @Html.ActionLink("Why Make This Site?", "Why", "Home")
        </div>
        <div class="three columns">
            <h5>How To</h5>
            <p>
                Clients

            </p>
            <p>
                Vets <br />
                @Html.ActionLink("Manage My Practice", "Manage", "HowTo") <br />
                @Html.ActionLink("Search For Places", "Search", "HowTo") <br />
                @Html.ActionLink("Work With Daylists", "DayLists", "HowTo")
            </p>
        </div>
        <div class="three columns">
            <h5>The Legal Bits</h5>
            @Html.ActionLink("Terms and Conditions", "Terms", "Legal") <br />
            @Html.ActionLink("Privacy Policy", "Privacy", "Legal")
        </div>
    </div>

</footer>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DYV</title>

    <link rel="stylesheet" href="~/dist/css/site.min.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css?family=Lobster|Raleway" rel="stylesheet" />

    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <nav>
        <div class="nav-section nav-brand-container">
            <i class="fa fa-navicon fa-2x nav-toggle"></i><a asp-controller="Home" asp-action="Index" class="nav-brand">DirectYourVet</a>
        </div>
        <div class="nav-section left-nav collapse-mobile">
            <ul>
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Home" asp-action="About">About</a></li>
                <li><a asp-controller="Home" asp-action="Contact">Contact Us</a></li>
            </ul>
        </div>        
            @await Html.PartialAsync("_LoginPartial")        
    </nav>

    <div class="main container">
        @RenderBody()
    </div>

    @await Html.PartialAsync("_FooterPartial")

        <script src="~/dist/js/vendor.js"></script>
        <script src="~/dist/js/modules/commons.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_MapScripts.cshtml
<environment names="Development">
    <script asp-append-version="true" src="~/dist/js/modules/maps.bundle.js"></script>
    @*<script src="https://maps.googleapis.com/maps/api/js?key=@ApiKeys.GetGoogleMapsApiKey()&callback=DYV.mapInit&libraries=places"
            async defer></script>*@
</environment>
<environment names="Staging,Production">
    <script src="~/js/modules/maps.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=@ApiKeys.GetGoogleMapsApiKey()&callback=DYV.mapInit&libraries=places"
            async defer></script>
</environment>

Views/Shared/_SharingScripts.cshtml
<script>
        window.twttr = (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0],
            t = window.twttr || {};
          if (d.getElementById(id)) return t;
          js = d.createElement(s);
          js.id = id;
          js.src = "https://platform.twitter.com/widgets.js";
          fjs.parentNode.insertBefore(js, fjs);

          t._e = [];
          t.ready = function(f) {
            t._e.push(f);
          };

          return t;
        }(document, "script", "twitter-wjs"));
</script>

<div id="fb-root"></div>
<div id="fb-root"></div>
<script>
        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8&appId=865107880292135";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
</script>

Views/Shared/_StripeScripts.cshtml
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>