Models/SubscriberDashboard/CreateDayListViewModel.cs
using DYV.Models.PlaceViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DYV.Models.SubscriberDashboard
{
    public class CreateDayListViewModel
    {
        public string name { get; set; }
        public DateTime dateAdded { get; set; }
        public List<PlaceSubscriberListItemViewModel> dayListPlaces { get; set; }
    }
}

Models/SubscriberDashboard/DayList.cs
using DYV.Models.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DYV.Models.SubscriberDashboard
{
    public class DayList
    {
        public int Id { get; set; }
        public string SubscriberUserId { get; set; }
        public SubscriberUser SubscriberUser { get; set; }

        public string Name { get; set; }
        public DateTime DateAdded { get; set; }
        public ICollection<PlaceDayList> PlaceDayLists { get; set; }

        public int allPlacesMapZoom { get; set; }
    }
}

Models/SubscriberDashboard/DayListCreationResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DYV.Models.SubscriberDashboard
{
    public class DayListCreationResult
    {
        public bool Success { get; set; }
        public List<string> Errors { get; set; }
    }
}

Models/SubscriberDashboard/DayListDashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DYV.Models.SubscriberDashboard
{
    public class DayListDashboardViewModel
    {
        public List<DayListViewModel> DayLists { get; set; }
    }
}

Models/SubscriberDashboard/DayListPlaceViewModel.cs
using DYV.Models.PlaceViewModels;
using DYV.Services.EFUpdate;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using DYV.Models.User;

namespace DYV.Models.SubscriberDashboard
{
    public class DayListPlaceViewModel
    {
        public DayListPlaceViewModel(Place place, int zoomLevel, int dayListId, ClientUser clientUser)
        {
            Place = new PlaceDetailsViewModel();
            Place.UpdateProperties(place, true);
            ClientName = clientUser.Name;
            ZoomLevel = zoomLevel;
            DayListId = dayListId;
        }

        public int DayListId { get; set; }
        public int ZoomLevel { get; set; }
        public string ClientName { get; set; }
        public PlaceDetailsViewModel Place { get; set; }
    }
}

Models/SubscriberDashboard/DayListViewModel.cs
using DYV.Models.PlaceViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DYV.Models.SubscriberDashboard
{
    public class DayListViewModel
    {
        public int id { get; set; }

        [Display(Name = "Name")]
        public string name { get; set; }

        [Display(Name = "Date Added")]
        public string dateAdded { get; set; }
        public List<DayListPlaceViewModel> dayListPlaces { get; set; }

        public int allPlacesMapZoom { get; set; }
    }
}

Models/SubscriberDashboard/SaveZoomLevelViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DYV.Models.SubscriberDashboard
{
    public class SaveZoomLevelViewModel
    {
        public int allPlacesMapZoom { get; set; }
        public IEnumerable<PlaceDayList> placeZooms { get; set; }
    }
}

Models/SubscriberDashboard/SubscriberDashboardAjaxSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DYV.Models.Ajax
{
    public class SubscriberDashboardAjaxSearchViewModel
    {
        public string ClientNameTerm { get; set; }
        public string PlaceNameTerm { get; set; }
        public string AddressTerm { get; set; }
        public int Page { get; set; }
        public int Take { get; set; }
    }
}

Models/SubscriberDashboard/SubscriberDashboardIndexViewModel.cs
using DYV.Models.PlaceViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DYV.Models.SubscriberDashboard
{
    public class SubscriberDashboardIndexViewModel
    {
        public string PracticeName { get; set; }
        public PlacesListViewModel<PlaceSubscriberListItemViewModel> Places { get; set; }
    }
}

Controllers/SubscriberDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DYV.Data;
using DYV.Models;
using Microsoft.AspNetCore.Authorization;
using DYV.Services.Places;
using DYV.Models.Ajax;
using DYV.Models.SubscriberDashboard;
using DYV.Services.Practices;
using System.Threading;
using DYV.Services.DayListService;
using DYV.Models.PlaceViewModels;

namespace DYV.Views
{
    [Authorize(Roles = "Subscriber, Admin")]
    public class SubscriberDashboardController : Controller
    {
        private readonly IPlacesService _placesService;
        private readonly IPracticesService _practiceService;
        private readonly IDayListService _dayListService;

        public SubscriberDashboardController(IPlacesService placesService, IPracticesService practiceService, IDayListService dayListService)
        {
            _placesService = placesService;
            _practiceService = practiceService;
            _dayListService = dayListService;
        }

        // GET: SubscriberDashboard
        public async Task<IActionResult> Index()
        {
            return View(new SubscriberDashboardIndexViewModel()
            {
                PracticeName = await _practiceService.GetCurrentUserPracticeName()
            });
        }

        // GET: SubscriberDashboard/3
        [Route("SubscriberDashboard/Admin/{practiceId}")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(int practiceId)
        {
            return View(new SubscriberDashboardIndexViewModel()
            {
                PracticeName = await _practiceService.GetPracticeNameById(practiceId)
            });
        }

        // GET: SubscriberDashboard/SearchPlaces/
        [Route("SubscriberDashboard/SearchPlaces")]
        public async Task<IActionResult> SearchPlaces(string placeTerm, string clientTerm, string addressTerm, int page, int take)
        {
            if (placeTerm == null)
                placeTerm = "";

            if (clientTerm == null)
                clientTerm = "";

            if (addressTerm == null)
                addressTerm = "";

            return Json(
                await _placesService.GetPlacesListViewModelForCurrentSubscriber(
                    new SubscriberDashboardAjaxSearchViewModel()
                    {
                        AddressTerm = addressTerm.ToLower(),
                        ClientNameTerm = clientTerm.ToLower(),
                        PlaceNameTerm = placeTerm.ToLower(),
                        Page = page - 1,
                        Take = take
                    }));     
        }

        // GET: SubscriberDashboard/Admin/3/SearchPlaces/
        [Route("SubscriberDashboard/Admin/{practiceId}/SearchPlaces")]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> SearchPlaces(int practiceId, string placeTerm, string clientTerm, string addressTerm, int page, int take)
        {
            if (placeTerm == null)
                placeTerm = "";

            if (clientTerm == null)
                clientTerm = "";

            if (addressTerm == null)
                addressTerm = "";

            return Json(
                await _placesService.GetPlacesListViewModelForPracticeIfAdmin(
                    practiceId,
                    new SubscriberDashboardAjaxSearchViewModel()
                    {
                        AddressTerm = addressTerm.ToLower(),
                        ClientNameTerm = clientTerm.ToLower(),
                        PlaceNameTerm = placeTerm.ToLower(),
                        Page = page - 1,
                        Take = take
                    }));
        }

        // GET: SubscriberDashboard/SaveDayList
        [Route("SubscriberDashboard/SaveDayList")]
        [Authorize(Roles = "Subscriber")]
        [HttpPost]
        public async Task<IActionResult> SaveDayList([FromBody] CreateDayListViewModel model)
        {
            return Json(await _dayListService.CreateDayList(model));
        }

        //GET: SubscriberDashboard/DayLists
        [Route("SubscriberDashboard/DayLists/")]
        [Authorize(Roles = "Subscriber")]
        public async Task<IActionResult> DayLists()
        {
            return Json(
                await _dayListService.GetDayListsForCurrentUser(5)
            );
        }

        //GET: SubscriberDashboard/DayLists
        [Route("SubscriberDashboard/DayLists/All")]
        [Authorize(Roles = "Subscriber")]
        public async Task<IActionResult> DayListsAll()
        {
            return View(
                await _dayListService.GetDayListsForCurrentUser()
            );
        }

        //GET: SubscriberDashboard/GetDayListDetails/17
        [Route("SubscriberDashboard/GetDayListDetails/{id}")]
        [Authorize(Roles = "Subscriber")]
        public async Task<IActionResult> GetDayListDetails(int id)
        {
            return Json(await _dayListService.GetDayList(id));
        }

        //GET: SubscriberDashboard/DayListDetails/17
        [Route("SubscriberDashboard/DayLists/{id}")]
        [Authorize(Roles = "Subscriber, PracticeManager")]
        public IActionResult DayListDetails(int id)
        {
            ViewData["dayListId"] = id;
            return View();
        }

        //GET: SubscriberDashboard/SaveDayListDetails
        [Route("SubscriberDashboard/SaveDayListDetails")]
        [Authorize(Roles = "Subscriber")]
        public async Task<IActionResult> SaveDayListDetails([FromBody] SaveZoomLevelViewModel model)
        {
            return Json(await _dayListService.UpdateZooms(model));
        }

        //GET: SubscriberDashboard/DeleteDayList/85
        [Route("SubscriberDashboard/DeleteDayList/{id}")]
        [Authorize(Roles = "Subscriber")]
        public async Task<IActionResult> DeleteDayList(int id)
        {
            return View(await _dayListService.GetDayList(id));
        }

        //GET: /SubscriberDashboard/Details/5
        [Authorize(Roles = ("Client, Subscriber, Admin"))]
        [Route("SubscriberDashboard/Details/{id?}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (!id.HasValue || id == null)
                return NotFound();

            PlaceDetailsViewModel place;

            if (User.IsInRole("Admin"))
                place = await _placesService.GetPlaceByIdForAdmin(id.Value);
            else
                place = await _placesService.GetPlaceById(id.Value);

            if (place == null)
                return NotFound();

            return View(place);
        }
    }
}

Views/SubscriberDashboard/DayListDetails.cshtml
@{ 
    ViewData["Title"] = "Day List Details";
}

<div data-bind="visible: noData">
    <div data-bind="visible: loading" class="text-center" style="padding-top:100px"><i class="fa fa-cog fa-spin fa-5x fa-fw"></i></div>

    <h2 data-bind="visible: errorData" style="display: none;">The daylist could not be found.</h2>
</div>
<div data-bind="visible: hasData" style="display: none;">
    <div class="row">
        <div class="twelve columns">
            <h4 data-bind="text: title"></h4>
            <hr />
            <p class="hidden-print">Use the interactive maps to view the place and the surrounding areas.  Adjust the zoom level to give the best view possible, then save the zoom levels with the Save Changes button at the bottom of the page.</p>
            <button class="btn btn-default" data-bind="click: printPage" value="Print Daylist">Print Daylist</button>
            <hr />
        </div>        
    </div>

    <div class="row">
        <div class="four columns">
            <h4>All Places</h4>
            <p>Click on or hover over the markers to see the name of the place.</p>
            <button data-bind="click: resetBounds">Reset Map Size</button>
        </div>
        <div class="eight columns">
            <div class="map" id="allPlacesMap"></div>
            <hr />
        </div>
    </div>

    <div id="rowContainer" data-bind="foreach: {data: dayList, afterRender: renderComplete.bind($data, rendered)}">
        <div class="row">
            <div class="four columns">
                <h4 data-bind="text: place.name()"></h4>
                <dl class="dl-horizontal">
                    <dt>Client Name</dt>
                    <dd data-bind="text: clientName"></dd>
                    <dt>Address</dt>
                    <dd data-bind="text: place.address1()"></dd>
                    <dt>City</dt>
                    <dd data-bind="text: place.city()"></dd>
                    <dt>County</dt>
                    <dd data-bind="text: place.county()"></dd>
                    <dt>Country</dt>
                    <dd data-bind="text: place.country()"></dd>
                    <dt>Post Code</dt>
                    <dd data-bind="text: place.postcode()"></dd>
                </dl>
            </div>
            <div class="eight columns">
                <div class="map" data-bind="attr: {id: divId}"></div>
                <hr />
            </div>
        </div>            
    </div>
    
    <div class="hidden-print">
        <button data-bind="click: saveZooms" type="button" value="Save Changes" class="btn btn-default">Save Changes</button>
    </div>
</div>

<div class="hidden-print">
    <a asp-action="DayListsAll">Back to All Daylists</a>
</div>

<input hidden id="dayListId" value='@ViewData["dayListId"]' />

@section Scripts {
    <script type="text/javascript" src="~/dist/js/modules/daylist.bundle.js"></script>
}

Views/SubscriberDashboard/DayListsAll.cshtml
@model DYV.Models.SubscriberDashboard.DayListDashboardViewModel

@{ 
    ViewData["Title"] = "Your Day Lists";
}

<h2>@ViewData["Title"]</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DayLists[0].name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DayLists[0].dateAdded)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.DayLists) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dateAdded)
            </td>
            <td>
                @Html.ActionLink("View DayList", "DayListDetails", "SubscriberDashboard", new { item.id }) |
                @Html.ActionLink("Delete", "DeleteDayList", new { item.id })
            </td>
        </tr>
}
    </tbody>
</table>

Views/SubscriberDashboard/DeleteDayList.cshtml
@model DYV.Models.SubscriberDashboard.DayListViewModel
@{
    ViewData["Title"] = "Confirm Delete";
}

<h2>Are you sure you want to delete this day list?</h2>
<div>
    <h4>@Html.DisplayFor(model => model.name)</h4>
    <hr />
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <button type="submit" value="Delete" class="btn btn-danger"><i class="fa fa-trash-o fa-lg"></i>Delete</button>
            <a  asp-action="DayListsAll" asp-controller="SubscriberDashboard" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>

Views/SubscriberDashboard/Details.cshtml
@model DYV.Models.PlaceViewModels.PlaceDetailsViewModel

<div>
    <h4>@Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <div id="map" class="map">
    </div>
    <input type="text" class="controls" placeholder="Search for your address" id="mapsearch" />
    <button id="myLocButton">Show me on the map</button>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Address1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address1)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.County)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.County)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Back To List", "Index", "SubscriberDashboard")
</div>



<input asp-for="Latitude" type="number" hidden />
<input asp-for="Longitude" type="number" hidden /> 
<input id="isSubscriber" value="subscriber" hidden />

@section Scripts {
    @{await Html.RenderPartialAsync("_MapScripts");}
}

Views/SubscriberDashboard/Index.cshtml
@model DYV.Models.SubscriberDashboard.SubscriberDashboardIndexViewModel

@{
    ViewData["Title"] = Model.PracticeName;
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="six columns">
        <form>
            <h4>Search</h4>
            <label for="searchClientName">Client Name:</label>
            <input type="text" data-bind="value: searchClient, valueUpdate:'keyup'" id="searchClientName" />

            <label for="searchPlaceName">Place Name:</label>
            <input type="text" data-bind="value: searchPlace, valueUpdate:'keyup'" id="searchPlaceName" />

            <label for="searchAddress">Address:</label>
            <input type="text" data-bind="value: searchAddress, valueUpdate:'keyup'" id="searchAddress" />

            <label for="resultsPerPage">Results per Page:</label>

            <select data-bind="options: resultSizes, value: numPerPage"></select><br />

            <button data-bind="click: clearSearch" type="button" value="Clear Search">Clear</button>
                    
        </form>
    </div>
    <div class="six columns">
        <div style="display:none;" data-bind="slideOutUp: startedDayList">
            <h4>New Day List</h4>
                <label for="dayListName">Daylist Name:</label>
                <input id="dayListName" class="u-full-width" type="text" data-bind="value: dayList().name" />

                <ul class="fa-ul" data-bind="template: {foreach: dayList().dayListPlaces, beforeRemove: dayList().fadeOut, afterAdd: dayList().fadeIn}">
                    <li>
                        <i class="fa fa-map-marker fa-lg fa-li" aria-hidden="true"></i>
                        <span data-bind="text: name"></span>
                        <a data-bind="click: $parent.dayList().removeFromList.bind($parent.dayList(), $data)"> Remove</a>
                    </li>
                </ul>

                <button class="button" type="button" data-bind="click: dayList().save.bind(dayList())"><i class="fa fa-2x fa-save"></i>Save</button>
                <button class="button" type="button" data-bind="click: dayList().tryDiscard.bind(dayList())"><i class="fa fa-2x fa-trash-o"></i>Discard</button>
        </div>
        <div style="display:none;" data-bind="slideOutUp: !startedDayList()">
            <h4>Recent Day Lists</h4>
            <ul class="fa-ul" data-bind="foreach: dayList().savedDayLists">
                <li>
                    <a data-bind="attr: {href: detailsUrl}">
                        <i class="fa fa-map-marker fa-lg fa-li" aria-hidden="true"></i>
                        <span data-bind="text: name"></span> (<span data-bind="text: dateAdded"></span>)
                    </a>
                </li>
            </ul>

            @Html.ActionLink("View All Daylists", "DayListsAll")
        </div>
    </div>
</div>

<div class="row table-top-pag">
    <ul class="pagination">
        <li>
            <a class="button" href="#" data-bind="click: setPage.bind($data, 1)">&laquo;</a>
        </li>
        <li>
            <a class="button" href="#" data-bind="click: setPage.bind($data, page() - 1)">&lt;</a>
        </li>
        <!-- ko foreach: pageArray -->
        <li>
            <a class="button" href="#" data-bind="click: $parent.setPage.bind($parent, $data + 1), text: $data + 1, css: {'button-primary': $data + 1 === $parent.page()}"></a>                
        </li>
        <!-- /ko -->
        <li>
            <a class="button" href="#" data-bind="click: setPage.bind($data, page() + 1)">&gt;</a>
        </li>
        <li>
            <a class="button" href="#" data-bind="click: setPage.bind($data, numPages())">&raquo;</a>
        </li>
    </ul>
</div>


<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th>Client Name</th>
                <th>Place Name</th>
                <th>Address</th>
                <th>City </th>
                <th>County</th>
                <th>Country </th>
                <th>Post Code</th>
                <th></th>
            </tr>
        </thead>
        <tbody style="display:none;" data-bind="foreach: places, visible: hasResults">
            <tr>
                <td data-bind="text: clientName"></td>
                <td data-bind="text: name"></td>
                <td data-bind="text: address1"></td>
                <td data-bind="text: city"></td>
                <td data-bind="text: county"></td>
                <td data-bind="text: country"></td>
                <td data-bind="text: postcode"></td>
                <td>
                    <a data-bind="attr: {href: detailsUrl}">Details</a> |
                    <a data-bind="click: $parent.dayList().addToList.bind($parent.dayList(), $data), visible: $parent.dayList().canAddToList($data)">Add to Day List</a>
                    <a data-bind="click: $parent.dayList().removeFromList.bind($parent.dayList(), $data), visible: $parent.dayList().canRemoveFromList($data)">Remove from Day List</a>
                </td>
            </tr>
        </tbody>
        <tbody data-bind="visible: !hasResults()">
            <tr>
                <td colspan="9" class="u-text-center">
                    <i class="fa fa-cog fa-spin fa-5x fa-fw"></i>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="show-only-mobile table-bottom-pag">
        <ul class="pagination">
            <li>
                <a class="button" href="#" data-bind="click: setPage.bind($data, 1)">&laquo;</a>
            </li>
            <li>
                <a class="button" href="#" data-bind="click: setPage.bind($data, page() - 1)">&lt;</a>
            </li>
            <!-- ko foreach: pageArray -->
            <li data-bind="">
                <a class="button" href="#" data-bind="click: $parent.setPage.bind($data, $data + 1), text: $data + 1, css: {'button-primary': $data + 1 === $parent.page()}"></a>
            </li>
            <!-- /ko -->
            <li>
                <a class="button" href="#" data-bind="click: setPage.bind($data, page() + 1)">&gt;</a>
            </li>
            <li>
                <a class="button" href="#" data-bind="click: setPage.bind($data, numPages())">&raquo;</a>
            </li>
        </ul>
    </div>
</div>



@section Scripts {
    <script src="~/dist/js/modules/dashboard.bundle.js"></script>
}